### ISSUE TITLE
Is Project abandoned?

### ISSUE THREAD

**Issue by alfishe** [path/android-priority-jobqueue#96]
Seems no active development/bugfixing performed on a project (at list publicly) for about half year.
Does that mean project abandoned by Path?
I plan to make it much more powerful and stable for my own purposes so want to know if I need to coordinate efforts with original development team or I can just develop my own fork without looking back.

Thanks in advance if Path representative can answer on this question.

**Comment by quiqueqs** [comment]
Also interested in knowing the status of this project. The wiki pages haven't been updates since 2013.

**Comment by belucid** [comment]
I work at Path. Fork and improve! It's the OSS way. No need to coordinate with us.

**Comment by Papipo** [comment]
Actually, there are many active forks. It would be nice to merge something or maybe change the canonical repository.

**Comment by mecid** [comment]
@Papipo i am using current stable release of Path. Which fork are you using?

**Comment by alfishe** [comment]
I just see that lots of issues still in unresolved state, unchecked pulls and other stuff. No support for latest development environment.

Ok, forked and will implement fixes and features there.
Thanks for responses.

**Comment by Papipo** [comment]
@mecid I am doing the same, although I wonder if it would be better to use some other fork.

**Comment by hoombar** [comment]
@belucid will pull requests be accepted? It looks like there are a few pending that are nearing a year old. As @yigit seems to be one of the core contributors, but has now gone to work for Google (I think?), I'm inclined to agree with @Papipo

**Comment by belucid** [comment]
No plans to merge any PRs at this point. The community ought to promote a fork as canonical and merge PRs there. I'm happy to update this repository to point to the new canonical fork.

**Comment by yigit** [comment]
I'm in talks w/ Path. We'll post a resolution tonight and we'll do whats necessary to keep it alive.

**Comment by yigit** [comment]
The resolution is that I'll continue on my fork. Maven groupId will change but project domain should stay the same. (so no necessary code changes except your gradle file)
github.com/yigit/android-priority-jobqueue

Is there any tool to easily move issues over to another repo? 

In terms of priorities, I'm hoping to finish up [tagging][1] first then get rid of ant (hey, it is year 2015) and continue w/ cancelation.

Btw, as i've mentioned in the cancelation ticket, don't expect too much from it. A job can only be cancelled if it has not started yet. But we can add necessary APIs so that jobs can check if they are canceled during a long onRun.

Hopefully, we can have a more streamlined process for contributions etc.

[1]: https://github.com/yigit/android-priority-jobqueue/tree/tags

**Comment by belucid** [comment]
There is this: https://github.com/google/github-issue-mover

**Comment by yigit** [comment]
Hmm, that didn't work, does not list forked repo. 
Thanks for the suggestion, I'll look around or keep replying here.

**Comment by yigit** [comment]
ok, it was not working because issues were disabled on forked projects by default.
I'll go over the issues and move the ones I see necessary.

**Comment by yigit** [comment]
ok, i've moved a bunch of tasks but not all as the tool started giving an error (API limit i assume).
Closing this task, please create any further issues at github.com/yigit/android-priority-jobqueue
